
(function(){
 const D=window.APP_DATA, nav=document.getElementById('nav'), grid=document.getElementById('grid'), filters=document.getElementById('filters');
 const q=document.getElementById('q'), sectionTitle=document.getElementById('sectionTitle'), sectionDesc=document.getElementById('sectionDesc'), sectionCount=document.getElementById('sectionCount'), mobileTitle=document.getElementById('mobileTitle');
 let current=(location.hash||'#especiais').slice(1), subgroup='Todos';
 const fmtSize=n=>{if(n<1024*1024)return Math.max(1,Math.round(n/1024))+' KB';return (n/1024/1024).toFixed(n>10*1024*1024?0:1)+' MB'};
 function escapeHtml(s){return String(s||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]))}
 function navBuild(){nav.innerHTML='';D.sections.forEach((s,i)=>{const b=document.createElement('button');b.dataset.id=s.id;b.innerHTML=`<span class="nicon">${String(i+1).padStart(2,'0')}</span><span>${escapeHtml(s.short)}</span><span class="count">${s.count}</span>`;b.onclick=()=>{location.hash=s.id;closeMenu()};nav.appendChild(b)})}
 function setSection(){let s=D.sections.find(x=>x.id===current)||D.sections[0];current=s.id;document.querySelectorAll('#nav button').forEach(b=>b.classList.toggle('active',b.dataset.id===current));sectionTitle.textContent=s.label;mobileTitle.textContent=s.short;sectionDesc.textContent=s.desc;sectionCount.textContent=s.count;subgroup='Todos';q.value='';buildFilters();render()}
 function buildFilters(){let arr=D.entries.filter(e=>e.section===current);let groups=['Todos',...new Set(arr.map(e=>e.subgroup).filter(Boolean))];groups.sort((a,b)=>a==='Todos'?-1:b==='Todos'?1:a.localeCompare(b,'pt-BR',{numeric:true}));filters.innerHTML='';groups.forEach(g=>{const b=document.createElement('button');b.textContent=g;b.className=g===subgroup?'active':'';b.onclick=()=>{subgroup=g;[...filters.children].forEach(x=>x.classList.toggle('active',x.textContent===g));render()};filters.appendChild(b)})}
 function viewerLink(e){const p=new URLSearchParams({file:e.openPath,title:e.title,type:e.type});return 'viewer.html?'+p.toString()}
 function card(e){const official=e.official?'<span class="pill official">JW/WOL</span>':'';const year=e.year?`<span class="pill">${escapeHtml(e.year)}</span>`:'';const lang=e.language?`<span class="pill">${escapeHtml(e.language)}</span>`:'';const num=e.number?`<span class="pill">Nº ${escapeHtml(e.number)}</span>`:'';const cat=e.catalogTitle?`<div class="catalog"><b>Catálogo:</b> ${escapeHtml(e.catalogTitle)}</div>`:'';const off=e.official?`<a class="gold" href="${escapeHtml(e.official)}" target="_blank" rel="noopener">Fonte JW/WOL</a>`:'';const dl=e.downloadPath?`<a href="${encodeURI(e.downloadPath)}" download>EPUB</a>`:'';const open=e.type==='PWA'?`<a class="primary" href="${encodeURI(e.openPath)}">Abrir módulo</a>`:`<a class="primary" href="${viewerLink(e)}">Abrir no leitor</a>`;return `<article class="card"><div class="meta"><span class="pill">${escapeHtml(e.type)}</span>${year}${lang}${num}${official}</div><h3>${escapeHtml(e.title)}</h3><div class="filename">${escapeHtml(e.filename)} · ${fmtSize(e.size)}</div>${cat}<div class="actions">${open}${off}${dl}</div></article>`}
 function render(){let term=q.value.trim().toLocaleLowerCase('pt-BR');let arr=D.entries.filter(e=>e.section===current&&(subgroup==='Todos'||e.subgroup===subgroup));if(term)arr=arr.filter(e=>(e.title+' '+e.filename+' '+e.year+' '+e.subgroup+' '+e.language+' '+e.catalogTitle).toLocaleLowerCase('pt-BR').includes(term));grid.innerHTML=arr.length?arr.map(card).join(''):'<div class="empty">Nenhum arquivo encontrado com este filtro.</div>';document.getElementById('visibleCount').textContent=arr.length}
 q.addEventListener('input',render);window.addEventListener('hashchange',()=>{current=(location.hash||'#especiais').slice(1);setSection()});navBuild();setSection();
 const side=document.getElementById('sidebar'),back=document.getElementById('backdrop');document.getElementById('menuBtn').onclick=()=>{side.classList.add('open');back.classList.add('show')};back.onclick=closeMenu;function closeMenu(){side.classList.remove('open');back.classList.remove('show')}
 // PWA install
 let deferred;const install=document.getElementById('installBtn');window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;install.style.display='inline-block'});install.onclick=async()=>{if(!deferred)return;deferred.prompt();await deferred.userChoice;deferred=null;install.style.display='none'};
 if('serviceWorker' in navigator && location.protocol!=='file:')navigator.serviceWorker.register('service-worker.js').catch(()=>{});
})();
