
(()=>{
const D=window.EEM_DATA;
const $=(s,r=document)=>r.querySelector(s), $$=(s,r=document)=>[...r.querySelectorAll(s)];
const nav=[['inicio','Inicio'],['programa','Programa EEM'],['disciplinas','Disciplinas'],['bibliografia','Bibliografía'],['complementario','Material complementario'],['momentos','Momentos especiales'],['archivo','Archivo personal'],['fotos','Fotos']];
const state={font:parseInt(localStorage.getItem('eem-font')||'18',10), fav:new Set(JSON.parse(localStorage.getItem('eem-fav')||'[]')), studied:new Set(JSON.parse(localStorage.getItem('eem-studied')||'[]'))};
document.documentElement.style.setProperty('--reader',state.font+'px');
const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
const normalizeRef=r=>String(r??'').replace(/½/g,'1/2').replace(/¼/g,'1/4').replace(/\s+/g,' ').trim();
const wolUrl=r=>'https://wol.jw.org/es/wol/s/r4/lp-s?q='+encodeURIComponent(normalizeRef(r));
const jwUrl=r=>'https://www.jw.org/es/b%C3%BAsquedas/?q='+encodeURIComponent(normalizeRef(r));
const refLinks=r=>{const n=normalizeRef(r);return `<span class="ref-pair"><a class="ref-link" href="${wolUrl(n)}" target="_blank" rel="noopener noreferrer">${esc(n)} · WOL ↗</a><a class="ref-jw" href="${jwUrl(n)}" target="_blank" rel="noopener noreferrer" aria-label="Buscar ${esc(n)} en JW.ORG">JW.ORG</a></span>`};
const disc=c=>D.program.find(x=>x.code===c);
const bib=c=>D.bibliography.find(x=>x.group===c);
const anomalyFor=c=>D.anomalies.filter(x=>x.item===c||x.item?.startsWith(c+'-'));
function shell(){
 document.body.innerHTML=`<div class="app-shell"><header class="topbar"><div class="topbar-inner"><a class="brand" href="#inicio"><span class="brand-mark">EEM</span><span><b>Acervo Ministerial</b><small>Clase 27 · estudio personal</small></span></a><div class="search-wrap"><input id="globalSearch" class="global-search" placeholder="Buscar unidad, tema o referencia…" autocomplete="off"><div id="searchResults" class="search-results"></div></div><button class="nav-toggle" aria-label="Abrir menú">☰</button></div></header><div class="layout"><aside class="sidebar"><nav class="nav-list">${nav.map(([id,l])=>`<a class="nav-link" data-nav="${id}" href="#${id}"><span class="dot"></span>${l}</a>`).join('')}</nav><div class="sidebar-note"><b>Fuentes oficiales</b><br>Las referencias del Progr-EEM abren búsquedas oficiales en WOL y JW.ORG. Para material histórico, WOL suele ofrecer la cobertura más completa.</div></aside><main id="main" class="main"></main></div></div><div id="modal" class="modal"><div class="modal-card"><div class="modal-head"><b id="modalTitle"></b><button class="close" aria-label="Cerrar">Cerrar</button></div><div id="modalBody" class="modal-body"></div></div></div>`;
 $('.nav-toggle').onclick=()=>$('.sidebar').classList.toggle('open'); $('.close').onclick=closeModal; $('#modal').addEventListener('click',e=>{if(e.target.id==='modal') closeModal()});
 setupSearch(); window.addEventListener('hashchange',route); route();
}
function setActive(id){$$('.nav-link').forEach(a=>a.classList.toggle('active',a.dataset.nav===id)); $('.sidebar').classList.remove('open')}
function pageHead(kicker,title,desc,actions=''){return `<div class="page-head"><div><div class="eyebrow" style="color:var(--gold)">${esc(kicker)}</div><h1>${esc(title)}</h1><p>${desc}</p></div>${actions}</div>`}
function footer(){return `<div class="footer">Escuela de Entrenamiento Ministerial · Clase 27. La bibliografía se abre mediante PDFs internos en español; las digitalizaciones JPG de lectura fueron retiradas y no se utiliza OCR defectuoso.</div>`}
function renderInicio(){setActive('inicio');const units=D.program.reduce((n,d)=>n+d.units.length,0),dig=D.program.filter(x=>x.digital_material).length,pdfPages=D.bibliography.reduce((n,x)=>n+(x.pages||0),0);$('#main').innerHTML=`<section class="hero"><div class="hero-copy"><div class="eyebrow">ACERVO DE ESTUDIO · CLASE 27</div><h1>Escuela de Entrenamiento Ministerial</h1><p>Programa, disciplinas, referencias y bibliografía en PDF reunidos en una navegación única para estudio personal.</p><div class="hero-actions"><a class="btn gold" href="#disciplinas">Abrir disciplinas</a><a class="btn light" href="#programa">Ver programa</a></div></div><div class="hero-art"><img src="assets/hero-composite-clase-27.png" alt="Clase 27"></div></section><div class="stats"><div class="stat"><b>${D.program.length}</b><span>disciplinas del programa</span></div><div class="stat"><b>${units}</b><span>unidades indexadas</span></div><div class="stat"><b>${dig}</b><span>disciplinas con bibliografía PDF</span></div><div class="stat"><b>${pdfPages}</b><span>páginas reunidas en PDF</span></div></div><div class="cards"><div class="card"><h2>Estudiar por unidad</h2><p>Abra una unidad para ver tema, semana, día, bibliografía del programa, observaciones de cotejo, notas personales y avance.</p><a class="btn" href="#disciplinas">Elegir disciplina</a></div><div class="card"><h2>Buscar referencias</h2><p>La búsqueda global localiza códigos como <i>w98 1/1 17</i>, temas y referencias del programa.</p><button class="btn" onclick="document.getElementById('globalSearch').focus()">Buscar ahora</button></div><div class="card"><h2>Programa EEM con enlaces</h2><p>El Progr-EEM de 14 páginas está incorporado al acervo. Sus referencias de publicaciones abren la fuente oficial en WOL; la vista por unidad también ofrece búsqueda en JW.ORG.</p><button class="btn" data-open-pdf>Abrir Progr-EEM</button></div></div>${footer()}`;bindCommon()}
function renderPrograma(){setActive('programa');const rows=D.program.map(d=>`<div class="card"><div class="discipline-letter">${d.code}</div><h2 style="margin-left:36px">${esc(d.label)}</h2><p class="meta">${d.unit_count} unidades · ${d.digital_material?'bibliografía PDF disponible':'programa indexado'}</p><a class="btn" href="#disciplina/${d.code}">Abrir unidades</a></div>`).join('');const an=D.anomalies.map(a=>`<div class="anomaly"><b>${esc(a.item)}</b><br><small>Programa: ${esc(a.pdf||'—')}</small>${a.digitalizacion?`<br><small>Digitalización cotejada: ${esc(a.digitalizacion)}</small>`:''}<br>${esc(a.status)}</div>`).join('');$('#main').innerHTML=`${pageHead('PROGRAMA EEM','Programa general e índice enlazado',`El Progr-EEM está incluido como PDF de ${D.sourcePdfPages||14} páginas. Se indexaron ${D.referenceCount||0} referencias bibliográficas; cada referencia puede abrirse en las fuentes oficiales.`,`<div class="head-actions"><button class="btn" data-open-pdf>PDF con enlaces</button><button class="btn ghost navy-text" data-open-original-pdf>PDF original</button></div>`)}<div class="official-source-strip"><a href="https://wol.jw.org/es/wol/h/r4/lp-s" target="_blank" rel="noopener"><b>WOL</b><span>Biblioteca en Línea Watchtower</span></a><a href="https://www.jw.org/es/biblioteca/" target="_blank" rel="noopener"><b>JW.ORG</b><span>Biblioteca oficial</span></a><span class="source-note">Las referencias históricas se dirigen principalmente a búsquedas de WOL; JW.ORG se ofrece como búsqueda complementaria.</span></div><div class="cards">${rows}</div><section style="margin-top:30px"><h2 class="section-title">Notas de cotejo</h2><div class="card">${an||'<div class="empty">Sin observaciones.</div>'}</div></section>${footer()}`;bindCommon()}
function renderDisciplinas(){setActive('disciplinas');$('#main').innerHTML=`${pageHead('ÍNDICE','Disciplinas','Seleccione una letra para estudiar sus unidades y referencias.')}<div class="cards">${D.program.map(d=>`<article class="card discipline-card"><span class="discipline-letter">${d.code}</span><h2>${esc(d.label)}</h2><p><b>${d.unit_count}</b> unidades</p><p class="meta">${d.digital_material?'<span class="badge green">Bibliografía PDF interna</span>':'<span class="badge">Programa disponible</span>'}</p><a class="btn" href="#disciplina/${d.code}">Ver unidades</a>${d.digital_material?` <a class="btn ghost" style="color:var(--navy)" href="#bibliografia/${d.code}">Bibliografía PDF</a>`:''}</article>`).join('')}</div>${footer()}`}
function renderDisciplina(code){setActive('disciplinas');const d=disc(code);if(!d)return render404();const weeks=[...new Set(d.units.map(u=>u.week).filter(Boolean))];$('#main').innerHTML=`${pageHead(`DISCIPLINA ${d.code}`,d.label,`${d.unit_count} unidades. Las referencias se conservan como aparecen en el programa fuente.`)}<div class="toolbar"><input id="unitFilter" placeholder="Filtrar por código, tema o referencia"><select id="weekFilter"><option value="">Todas las semanas</option>${weeks.map(w=>`<option value="${w}">Semana ${w}</option>`).join('')}</select>${d.digital_material?`<a class="btn" href="#bibliografia/${d.code}">Abrir bibliografía PDF</a>`:''}</div><div id="unitList" class="unit-list"></div>${footer()}`;const draw=()=>{const q=$('#unitFilter').value.toLowerCase().trim(),w=$('#weekFilter').value;const arr=d.units.filter(u=>(!w||String(u.week)===w)&&(!q||`${u.code} ${u.title} ${u.references_pdf}`.toLowerCase().includes(q)));$('#unitList').innerHTML=arr.map(u=>`<a class="unit-row" href="#unidad/${u.code}"><div class="unit-code">${esc(u.code)}</div><div><div class="unit-title">${esc(u.title||'Título no indicado')}</div><div class="unit-refs">${esc(u.references_pdf||'Sin referencias registradas')}</div></div><span class="week-chip">Semana ${u.week??'—'} · Día ${u.day??'—'}</span></a>`).join('')||'<div class="empty">No se encontraron unidades.</div>'};$('#unitFilter').oninput=draw;$('#weekFilter').onchange=draw;draw()}
function findUnit(code){for(const d of D.program){const u=d.units.find(x=>x.code===code);if(u)return [d,u]}return [null,null]}
function renderUnidad(code){const [d,u]=findUnit(code);setActive('disciplinas');if(!u)return render404();const refs=(u.references||[]).map(refLinks).join('');const anomalies=D.anomalies.filter(a=>a.item===u.code);const validations=D.validations.filter(v=>v.item===u.code||v.item===`${u.code}-${u.code}`); const idx=d.units.findIndex(x=>x.code===u.code),prev=d.units[idx-1],next=d.units[idx+1];$('#main').innerHTML=`${pageHead(`${d.code} · ${d.label}`,`${u.code} — ${u.title||'Título no indicado'}`,`Semana ${u.week??'—'} · Día ${u.day??'—'}`)}<div class="unit-detail"><article class="reader"><h2>Bibliografía del programa</h2><p class="source-ref">${esc(u.references_pdf||'Sin referencias registradas en el programa.')}</p><div class="ref-list">${refs}</div><p class="official-hint">WOL abre la búsqueda oficial de la referencia exacta; JW.ORG ofrece una segunda búsqueda dentro del sitio oficial.</p>${anomalies.length?`<h3>Observación de cotejo</h3>${anomalies.map(a=>`<div class="anomaly"><b>${esc(a.status)}</b><br>PDF: ${esc(a.pdf||'—')}${a.digitalizacion?`<br>Digitalización cotejada: ${esc(a.digitalizacion)}`:''}</div>`).join('')}`:''}${validations.length?`<h3>Validación de muestra</h3>${validations.map(v=>`<div class="anomaly"><b>${esc(v.status)}</b><br>${esc(v.detalhe)}</div>`).join('')}`:''}<h3>Ruta de estudio sugerida</h3><p>1. Revise el tema y las referencias del programa. 2. Consulte la bibliografía PDF cuando esté disponible. 3. Use los enlaces WOL o JW.ORG para localizar la publicación oficial. 4. Registre sus notas personales en el panel lateral.</p>${d.digital_material?`<a class="btn" href="#bibliografia/${d.code}">Abrir bibliografía PDF de ${d.code}</a>`:`<div class="empty">No se recibió bibliografía PDF para esta disciplina. El programa permanece disponible como índice.</div>`}<div class="toolbar" style="justify-content:space-between;margin-top:28px">${prev?`<a class="btn ghost" style="color:var(--navy)" href="#unidad/${prev.code}">← ${prev.code}</a>`:'<span></span>'}${next?`<a class="btn" href="#unidad/${next.code}">${next.code} →</a>`:''}</div></article><aside class="side-panel"><div class="panel"><h3>Mi estudio</h3><div class="checks"><button class="toggle-btn" data-fav="${u.code}">☆ Favorito</button><button class="toggle-btn" data-studied="${u.code}">✓ Estudiado</button></div><div class="progressbar"><span style="width:${Math.round(100*state.studied.size/D.program.reduce((n,x)=>n+x.units.length,0))}%"></span></div></div><div class="panel"><h3>Notas personales</h3><textarea class="note-area" data-note="${u.code}" placeholder="Escriba aquí observaciones de estudio…"></textarea><small>Se guardan solamente en este navegador.</small></div><div class="panel"><h3>Tamaño de lectura</h3><div class="checks"><button class="toggle-btn" data-font="-1">A−</button><button class="toggle-btn" data-font="1">A+</button></div></div></aside></div>${footer()}`;bindStudy(u.code)}
function renderBibliografia(code,initialPage){
 setActive('bibliografia');
 if(!code){$('#main').innerHTML=`${pageHead('BIBLIOGRAFÍA EN PDF','Bibliografía','Las seis disciplinas con material disponible se abren como PDFs internos en español. También se incluye el Progr-EEM con enlaces oficiales.')}<div class="cards"><article class="card discipline-card program-card"><span class="discipline-letter">EEM</span><h2>Progr-EEM</h2><p>${D.sourcePdfPages||14} páginas · referencias enlazadas</p><button class="btn" data-open-pdf>Abrir programa</button></article>${D.bibliography.map(b=>`<article class="card discipline-card"><span class="discipline-letter">${b.group}</span><h2>${esc(b.title)}</h2><p>${b.pages||0} páginas · PDF</p><a class="btn" href="#bibliografia/${b.group}">Abrir PDF</a></article>`).join('')}</div>${footer()}`;bindCommon();return}
 const b=bib(code);if(!b||!b.pdf)return render404();const total=b.pages||1;let current=Math.max(1,Math.min(total,Number(initialPage)||1));
 $('#main').innerHTML=`${pageHead(`BIBLIOGRAFÍA ${b.group}`,b.title,`${total} páginas · PDF interno en español`, `<a class="btn" href="#disciplina/${b.group}">Ver unidades</a>`)}<div class="scan-toolbar"><div class="scan-nav"><button class="btn ghost" id="prevPdf">← Anterior</button><span id="pdfCounter" class="badge"></span><button class="btn" id="nextPdf">Siguiente →</button></div><div class="scan-page-select"><label for="pdfPageSelect">Ir a</label><select id="pdfPageSelect">${Array.from({length:total},(_,i)=>`<option value="${i+1}">Página ${i+1}</option>`).join('')}</select></div><div class="scan-zoom"><button class="toggle-btn" id="reloadPdf">Recargar página</button><button class="toggle-btn" id="openFullPdf">Pantalla completa</button></div></div><div class="bibliography-layout"><div class="page-menu" aria-label="Páginas del PDF">${Array.from({length:total},(_,i)=>`<button class="page-link" data-page="${i+1}">Página ${i+1}</button>`).join('')}</div><article class="scan-reader"><div class="scan-note">PDF interno. Los botones de página fuerzan la recarga del visor para que el salto funcione también en navegadores que ignoran cambios simples del fragmento #page. En celular puede usar el selector “Ir a”.</div><div id="pdfLoading" class="pdf-loading" aria-live="polite">Cargando página…</div><iframe id="bibPdfFrame" class="pdf-frame" title="${esc(b.title)}"></iframe></article></div>${footer()}`;
 const frame=$('#bibPdfFrame'),loading=$('#pdfLoading'),sel=$('#pdfPageSelect');
 const pageUrl=n=>{const base=b.pdf;const sep=base.includes('?')?'&':'?';const bust=location.protocol==='file:'?'':`${sep}eemPage=${n}`;return `${base}${bust}#page=${n}&toolbar=0&navpanes=0&scrollbar=1&view=FitH`};
 const loadFrame=n=>{loading.classList.add('show');frame.onload=()=>loading.classList.remove('show');const url=pageUrl(n);frame.src='about:blank';setTimeout(()=>{frame.src=url},30)};
 const show=(n,force=false)=>{current=Math.max(1,Math.min(total,Number(n)||1));$('#pdfCounter').textContent=`Página ${current} de ${total}`;sel.value=String(current);$$('.page-link').forEach(x=>x.classList.toggle('active',Number(x.dataset.page)===current));$('#prevPdf').disabled=current<=1;$('#nextPdf').disabled=current>=total;history.replaceState(null,'',`#bibliografia/${b.group}/${current}`);const active=$(`.page-link[data-page="${current}"]`);active?.scrollIntoView({block:'nearest',inline:'nearest'});loadFrame(current)};
 $$('.page-link').forEach(x=>x.onclick=()=>show(Number(x.dataset.page)));$('#prevPdf').onclick=()=>show(current-1);$('#nextPdf').onclick=()=>show(current+1);sel.onchange=()=>show(Number(sel.value));$('#reloadPdf').onclick=()=>show(current,true);$('#openFullPdf').onclick=()=>openBibPdf(b,current);document.onkeydown=e=>{if(!location.hash.startsWith(`#bibliografia/${b.group}`))return;if(e.key==='ArrowLeft')show(current-1);if(e.key==='ArrowRight')show(current+1)};show(current)
}
function renderComplementario(){setActive('complementario');$('#main').innerHTML=`${pageHead('MATERIAL CONSERVADO','Material complementario','Contenido ya presente en el paquete anterior. Se mantiene separado porque estas transcripciones están en portugués, mientras la bibliografía principal se conserva en español.')}<div class="supplemental-list">${D.supplemental.map(x=>`<details class="card supplemental-item"><summary><b>${esc(x.label||x.title||x.group)}</b> <span class="badge">PT</span></summary><div class="reader supplemental-reader"><div class="ocr-page">${esc(x.text)}</div></div></details>`).join('')}</div>${footer()}`}
function renderMomentos(){setActive('momentos');$('#main').innerHTML=`${pageHead('MEMORIA DE LA CLASE','Momentos especiales','Discursos y material especial preservados dentro del acervo.')} ${D.specialMoments.map(x=>`<details class="moment"><summary>${esc(x.title||x.label||x.id)}</summary>${x.audio?`<audio class="audio" controls preload="metadata" src="${x.audio}"></audio>`:''}<pre>${esc(x.text)}</pre></details>`).join('')}${footer()}`}
function renderArchivo(){setActive('archivo');$('#main').innerHTML=`${pageHead('MEMORIA PERSONAL','Archivo personal','Documentos e imágenes personales. Los dos archivos previamente excluidos no forman parte de esta reconstrucción.')}<div class="archive-grid">${D.archive.map(x=>`<div class="archive-item" data-image="${x.path}" data-title="${esc(x.name)}"><img loading="lazy" src="${x.path}" alt="${esc(x.name)}"><div>${esc(x.name)}</div></div>`).join('')}</div>${footer()}`;bindImages()}
function renderFotos(){setActive('fotos');$('#main').innerHTML=`${pageHead('MEMORIA FOTOGRÁFICA','Fotos','Seis grupos preservados y normalizados para funcionar correctamente en HTTP, HTTPS y GitHub Pages.')}<div class="gallery-groups">${D.photoGroups.map(g=>`<section><h2 class="section-title">${esc(g.name)}</h2><div class="gallery">${g.items.map(x=>`<div class="photo" data-image="${x.path}" data-title="${esc(x.name)}"><img loading="lazy" src="${x.path}" alt="${esc(x.name)}"><span>${esc(x.name)}</span></div>`).join('')}</div></section>`).join('')}</div>${footer()}`;bindImages()}
function bindStudy(code){const n=$(`[data-note="${code}"]`);n.value=localStorage.getItem('eem-note-'+code)||'';n.oninput=()=>localStorage.setItem('eem-note-'+code,n.value);const f=$(`[data-fav="${code}"]`),s=$(`[data-studied="${code}"]`);const paint=()=>{f.classList.toggle('on',state.fav.has(code));f.textContent=state.fav.has(code)?'★ Favorito':'☆ Favorito';s.classList.toggle('on',state.studied.has(code));s.textContent=state.studied.has(code)?'✓ Estudiado':'○ Marcar estudiado'};f.onclick=()=>{state.fav.has(code)?state.fav.delete(code):state.fav.add(code);localStorage.setItem('eem-fav',JSON.stringify([...state.fav]));paint()};s.onclick=()=>{state.studied.has(code)?state.studied.delete(code):state.studied.add(code);localStorage.setItem('eem-studied',JSON.stringify([...state.studied]));paint()};$$('[data-font]').forEach(b=>b.onclick=()=>{state.font=Math.max(15,Math.min(24,state.font+Number(b.dataset.font)));localStorage.setItem('eem-font',state.font);document.documentElement.style.setProperty('--reader',state.font+'px')});paint()}
function bindCommon(){$$('[data-open-pdf]').forEach(b=>b.onclick=()=>openPdf());$$('[data-open-original-pdf]').forEach(b=>b.onclick=()=>openOriginalPdf())}
function bindImages(){$$('[data-image]').forEach(el=>el.onclick=()=>openImage(el.dataset.image,el.dataset.title))}
function openImage(src,title){$('#modalTitle').textContent=title||'Imagen';$('#modalBody').innerHTML=`<img src="${src}" alt="${esc(title)}">`;$('#modal').classList.add('open')}
function openBibPdf(b,page=1){const sep=b.pdf.includes('?')?'&':'?';const bust=location.protocol==='file:'?'':`${sep}eemPage=${page}`;$('#modalTitle').textContent=`${b.group} · ${b.title} · página ${page}`;$('#modalBody').innerHTML=`<iframe src="${b.pdf}${bust}#page=${page}&toolbar=1&navpanes=0&scrollbar=1&view=FitH" title="${esc(b.title)}"></iframe>`;$('#modal').classList.add('open')}
function openPdf(){ $('#modalTitle').textContent='Progr-EEM · referencias oficiales enlazadas'; $('#modalBody').innerHTML=`<iframe src="${D.sourcePdf}#toolbar=1&navpanes=0&scrollbar=1" title="Progr-EEM con enlaces"></iframe>`; $('#modal').classList.add('open') }
function openOriginalPdf(){ $('#modalTitle').textContent='Progr-EEM · PDF original'; $('#modalBody').innerHTML=`<iframe src="${D.sourcePdfOriginal||D.sourcePdf}#toolbar=1&navpanes=0&scrollbar=1" title="Progr-EEM original"></iframe>`; $('#modal').classList.add('open') }
function closeModal(){$('#modal').classList.remove('open');$('#modalBody').innerHTML=''}
function setupSearch(){let timer;const inp=$('#globalSearch'),box=$('#searchResults');inp.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>search(inp.value),120)});inp.addEventListener('keydown',e=>{if(e.key==='Escape'){box.classList.remove('open');inp.blur()}});document.addEventListener('click',e=>{if(!e.target.closest('.search-wrap'))box.classList.remove('open')});function search(q){q=q.trim().toLowerCase();if(q.length<2){box.classList.remove('open');return}let res=[];for(const d of D.program)for(const u of d.units){const hay=`${u.code} ${u.title} ${u.references_pdf}`.toLowerCase();if(hay.includes(q))res.push({href:`#unidad/${u.code}`,title:`${u.code} — ${u.title}`,meta:`${d.label} · ${u.references_pdf}`})}res=res.slice(0,22);box.innerHTML=res.length?res.map(r=>`<a class="search-item" href="${r.href}"><b>${esc(r.title)}</b><small>${esc(r.meta)}</small></a>`).join(''):'<div class="empty">Sin resultados.</div>';box.classList.add('open');$$('.search-item',box).forEach(a=>a.onclick=()=>box.classList.remove('open'))}}
function render404(){setActive('inicio');$('#main').innerHTML=`<div class="empty"><h2>No se encontró el contenido solicitado.</h2><a class="btn" href="#inicio">Volver al inicio</a></div>`}
function route(){const h=(location.hash||'#inicio').slice(1),parts=h.split('/'),r=parts[0],arg=parts[1];if(r==='inicio')renderInicio();else if(r==='programa')renderPrograma();else if(r==='disciplinas')renderDisciplinas();else if(r==='disciplina')renderDisciplina((arg||'').toUpperCase());else if(r==='unidad')renderUnidad((arg||'').toUpperCase());else if(r==='bibliografia')renderBibliografia((arg||'').toUpperCase(),parts[2]);else if(r==='complementario')renderComplementario();else if(r==='momentos')renderMomentos();else if(r==='archivo')renderArchivo();else if(r==='fotos')renderFotos();else render404();window.scrollTo(0,0)}
shell();
if('serviceWorker' in navigator && location.protocol.startsWith('http')) navigator.serviceWorker.register('./sw.js').catch(()=>{});
})();
